### ISSUE TITLE
Code for matching components.

### ISSUE THREAD

**Issue by NippunSharma** [BerkeleyHCI/vst#1]
Hi Authors,
I found your paper very interesting. I want to know if you will be releasing the code for:
1. creating the graph representation of vectors.
2. matching the components from target to source.
3. transferring style (stroke, fill, stroke-width, etc.) from source to target.

Hoping for a quick response.
Thanks!

**Comment by jeremywrnr** [comment]
This app has code for transferring style (3), but 1/2 won't be released as they're part of a previous project with Adobe.

With that said, the technique for 1/2 is specified in this paper: https://jeremywrnr.com/GraphKernel/
